### ISSUE TITLE
[Request] Icons for Foliate, Gimp and Kazam

### ISSUE THREAD

**Issue by pranshuj73** [yeyushengfan258/Win10Sur-icon-theme#2]
- [ ] **Foliate**
Comment=View eBooks
Icon=com.github.johnfactotum.Foliate
[Icon Link](https://github.com/johnfactotum/foliate/blob/master/data/com.github.johnfactotum.Foliate.svg)

- [ ] **GIMP**
Comment=Create, reorganize, and delete partitions
Icon=gimp
[Icon Link](https://en.wikipedia.org/wiki/GIMP#/media/File:The_GIMP_icon_-_gnome.svg)

- [ ] **Kazam**
Comment=Record a video or take a screenshot of your screen
Icon=kazam
[Icon Link](https://github.com/hzbd/kazam/blob/master/data/icons/128x128/apps/kazam.png)

Please make Icons for these ☝ apps. Also, I really like your work!

**Comment by yeyushengfan258** [comment]
OK
